Added TODO Comment
CSC207-UofT/course-project-internet-explorers pull request #49
Opened 2021-11-23 22:46 UTC by mdawess

Done to start linking with issues

2021-12-01 00:00 UTC, Philip-Nicolas requested changes
this PR includes good changes and is a solid WIP in the right direction, but it doesn't address the implications of those changes.

In my experience, code reviews have usually been done when the code is almost ready to be merged, so I came in expecting the program to run and the tests to pass. Yet, I found that the code doesn't even compile.
Not a problem btw, I'm just sharing the mindset I had while reviewing these changes 🤙

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
>      private boolean verifyId(UUID id) {
we could make verifyId return the casted `GameCharacter` object to avoid all the extra casts in this whole class
if the verification fails, we should just throw a `RuntimeException` since it would be a programmer error

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntityManager.java
>      }
this code will be further refactored once I finish & commit the work done by Roy and I yesterday – mainly we make a CreateEntity method in the manager and no longer use the WorldEntity constructor directly

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
> -    }
nice !

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntity.java
> +    }
I realized that these make more sense here as I was writing why i disagreed with moving

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntity.java
> +    public void setLinearVelocity(UUID id, Vector2 velocity) {
remove `id` param

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntity.java
> +    public void setTeleportVelocity(UUID id, Vector2 target, float dt) {
remove `id` param

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntity.java
> +    public void setTeleportVelocity(UUID id, Vector2 target, float dt) {
tbh we can remove this whole method, it's bad and useless and idk why I wrote it

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntity.java
> +        this.body = null;
can simply remove, being null means it's not set to anything

don't need to fix, constructor will be further refactored coming soon

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/presenters/levels/CameraManager.java
> +        subjectID = new WorldEntity().id;
new world entity won't be in the entitymanager, need to call the create/register method

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntityManager.java
>          body.setTransform(target, body.getAngle());
could be one line

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntityManager.java
>          body.setTransform(target, body.getAngle());
pretty sure I wrote this originally lmao

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/WorldEntityWithSprite.java
>      }
empty constructor is redundant, calling `super()` happens automatically, so you can remove this whole constructor

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/types/characters/GameCharacter.java
> +        super();
can remove `super()` call, since it happens automatically 

(happens automatically unless you invoke superconstructor with arguments)

2021-12-01 00:00 UTC, matrix-marker commented on src/test/java/characterTests/TestCharacterManager.java
> +        player3 = new Character();
characters aren't registered in the manager, so tests will fail

2021-12-01 00:00 UTC, matrix-marker commented on src/main/java/core/worldEntities/types/characters/GameCharacter.java
> -public class Character extends WorldEntityWithSprite {
rename from previously merged PR is undone, should be reverted

2021-12-01 00:00 UTC, matrix-marker commented on src/test/java/characterTests/TestCharacterManager.java
> +        player3 = new Character();
also, `addCharacter` method was removed, but tests remain

other tests use characterEntities map – they should be updated or simply removed

2021-12-01 00:00 UTC, matrix-marker commented on src/test/java/world/TestWorldEntity.java
> +        WorldEntity entity = new WorldEntity();
entity won't be registered in the manager, so this test will fail

2021-12-01 00:00 UTC, matrix-marker commented on src/test/java/world/TestWorldEntity.java
> +        WorldEntity entity = new WorldEntity();
same with those below

2021-12-01 00:57 UTC, roylin2000 reviewed
Yea I agree with everything that Phil-Nic has said. And as he mentioned, we have done some other refactoring that will combine with this one.

2021-12-04 18:28 UTC, Philip-Nicolas requested changes
PR is good, requested small changes as TODO list for myself to address

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntity.java
> +    public void setBody(Body body) {this.body = body;}
should be `protected`

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntity.java
>      public final UUID id;
should be `private`

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntityManager.java
> +    * Creates a GameCharacter
outdated comment

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntityManager.java
> +    public void teleport(UUID id, Vector2 target) {
probably unused, also is unsafe to use (can cause weird behaviour); remove

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntityManager.java
> +    public int getNumEntities() {
check if used, also could rename to `getEntityCount`

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntityWithSprite.java
> +        sprite.setRotation(this.getBody().getAngle() * 57.29578f);
add comment for radians->degrees angle conversion

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/WorldEntityWithSprite.java
>          this.offset = new Vector2(-sprite.getOriginX(), -sprite.getOriginY());
add issue to document how sprite & body geometry work relative to eachother

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
> +            // Moved this to be a setter in the entity class
don't need comment saying code was moved

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
> +                usageDelegate.use((Weapon) ((GameCharacter) this.entityManager.getEntity(id)).getInventory().get(0));
should invoke verify method instead of casting

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
>      public void updateLevel(UUID id) {
add issue to make name reflect what method does

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
> +        verifyId(id).setHealth(verifyId(id).getHealth() - damage);
add issue to make name reflect what method does

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
>           * Checks if the item is in the character's inventory and then returns true if it is.
add issue to make name reflect what method does

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
>      public boolean selectItem(UUID id, Item item) {
add issue to make name reflect what method does (`swapHeldItem `or similar)

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
> +            );
could use local var

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
>          /*
add issue to make name reflect what method does (`addItemToInventory`)

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/CharacterManager.java
>      public boolean removeInventory(UUID id, Item item) {
add issue to make name reflect what method does (`removeItemFromInventory`)

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/main/java/core/worldEntities/types/characters/GameCharacter.java
> -public class Character extends WorldEntityWithSprite {
was not reverted ?

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/test/java/characterTests/TestWorldEntityManager.java
> +        // Should add another form of entity to test this
currently passes, comment out whole thing instead of empty passing test

2021-12-04 18:28 UTC, Philip-Nicolas commented on src/test/java/characterTests/TestWorldEntityManager.java
> +        // Should add another form of entity to test this
or add TODO comment

2021-12-05 00:49 UTC, Philip-Nicolas approved these changes

2021-12-05 19:06 UTC, merged