Inventory testing
CSC207-UofT/course-project-internet-explorers pull request #67
Opened 2021-12-03 19:07 UTC by aki2000ful

inventory tests now pass

2021-12-03 22:26 UTC, roylin2000 requested changes
Next time, you can merge this into your refactoring branch first since some changes here look identical to that. I'm not sure about the most proper process. Other than my comment in the code, it looks  good!

2021-12-03 22:26 UTC, roylin2000 commented on src/test/java/InventorySystem/TestInventory.java
>          comparison.add(dagger);
I think you forgot to add an assert here.

2021-12-04 19:22 UTC, Philip-Nicolas requested changes
the tests `testDamage` and `testInventory` effectively end up testing the LIst wrapper methods in Character

we want to be testing that you can properly manage that list from the CharacterManager, but now the only method that does that is `testSelect` – we have `addInventory` and `removeInventory` etc in the manager, and testing those ensures that the whole implementation works

the 2 tests mentioned could be moved to smth like `testCharacter`, and `TestInventory` needs more tests of the use-case

2021-12-04 19:22 UTC, Philip-Nicolas commented on src/test/java/InventorySystem/TestInventory.java
>          Item dagger = new Dagger(2);
these could be global to the class instead of declaring the exact same items over and over

2021-12-06 03:10 UTC, Philip-Nicolas approved these changes
tests are much more effective

2021-12-06 03:54 UTC, Philip-Nicolas approved these changes

2021-12-06 03:55 UTC, merged