rework input system
CSC207-UofT/course-project-internet-explorers pull request #79
Opened 2021-12-08 07:17 UTC by Philip-Nicolas

more clean, less coupled, & more extendable

2021-12-08 16:27 UTC, mdawess requested changes
Great changes, just a few comments!

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/AIInputDevice.java
> +    private final InputProvider<Character.Input> characterInputProvider = () -> new Character.Input(new Vector2(-1, 0), false);
Nice! Could you please comment for readability

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/InputController.java
>  public class InputController {
The controller class should take in inputs, package them and then pass them down to the use case layer. Is this just meant to be an intermediary class? If so, could it be an interface?

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/InputManager.java
> +public class InputManager {
Is this meant to be a use case? Just want to confirm level. Also, please comment

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/InputMapping.java
> +    public InputMapping(InputProvider<T> provider, InputHandler<T> handler) {
This seems to be awkwardly between layers. The provider would be a controller and the handler is a use case. Why not just directly pass arguments from the provider to the handler without the middleman

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/InputMapping.java
> +    public InputMapping(InputProvider<T> provider, InputHandler<T> handler) {
I noticed input provider is an interface - why are you instantiating?

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/KeyboardInputDevice.java
Please comment for readability

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/input/KeyboardInputDevice.java
> +    private final InputProvider<core.presenters.HUD.HudInput> hudInputInputProvider = () ->
Why not import to make the code cleaner

2021-12-08 16:27 UTC, mdawess commented on src/main/java/core/presenters/levels/LevelGameplayController.java
>      public void show() {
please comment this more

2021-12-08 19:43 UTC, roylin2000 reviewed
As Michael mentioned, more JavaDocs would be nice to have. Otherwise, everything seems to work fine, so I'm fine with this :D

2021-12-08 20:16 UTC, Philip-Nicolas commented on src/main/java/core/input/InputController.java
>  public class InputController {
definitely worth explaining:

if in the future, AI inputs will depend on the state of the world, this controller class would take care of providing that input by storing the LevelManager, for example

2021-12-08 21:17 UTC, Philip-Nicolas commented on src/main/java/core/input/AIInputDevice.java
> +    private final InputProvider<Character.Input> characterInputProvider = () -> new Character.Input(new Vector2(-1, 0), false);
this is a shorthand that I didn't even know existed until intellij prompted me to change what I had before

reworking this led me to do a Big Refactor which helped a Lot

2021-12-08 21:41 UTC, Philip-Nicolas commented on src/main/java/core/presenters/levels/LevelGameplayController.java
>      public void show() {
not sure what's unclear; I think this class has the least changes in the whole PR

could you be more specific?

2021-12-08 21:42 UTC, Philip-Nicolas reviewed
much improved over previous version imo

could still be tested using headless tests class

2021-12-09 01:52 UTC, mdawess approved these changes

2021-12-09 01:52 UTC, mdawess commented on src/main/java/core/input/InputController.java
>  public class InputController {
makes sense

2021-12-09 01:56 UTC, merged